namespace: reverse-words-production
commonLabels:
  app: reversewords-prod
bases:
- github.com/thurdias/quarkus-cicd-ofc/tree/main/k8s
resources:
- namespace.yaml
#- ingress.yaml
- route.yaml
patchesStrategicMerge:
- deployment.yaml