apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thurdias/quarkus-cicd-ofc.git
    targetRevision: HEAD
    path: k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: quarkus-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
