apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-stage
spec:
  project: default
  source:
    repoURL: https://github.com/my-org/cicd-repo.git
    targetRevision: HEAD
    path: k8s/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: quarkus-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
