apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      description: The URL of the Git repository to clone
      type: string
    - name: revision
      description: The git revision (branch, tag, or commit) to clone
      type: string
      default: "main"
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: lint
      taskRef:
        name: lint-task
      runAfter: [git-clone]
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: test
      taskRef:
        name: test-task
      runAfter: [lint]
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: build
      taskRef:
        name: build-task
      runAfter: [test]
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: push-image
      taskRef:
        name: push-image-task
      runAfter: [build]
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: update-manifest
      taskRef:
        name: update-manifest-task
      runAfter: [push-image]
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
