apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: promotion-pipeline
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      description: The URL of the Git repository to clone
      type: string
    - name: revision
      description: The git revision (branch, tag, or commit) to clone
      type: string
      default: "main"
  tasks:
    - name: get-stage-config
      taskRef:
        name: git-clone
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: run-tests
      taskRef:
        name: test-task 
      runAfter: [get-stage-config]
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: create-pr
      taskRef:
        name: create-pr-task
      runAfter: [run-tests]
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
