apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: build
      image: maven:3.8.1-openjdk-17
      script: |
        cd /workspace/shared-workspace/clone-dir
        mvn package
