apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: build
      image: maven:3.6.3-jdk-8
      script: |
        cd /workspace/shared-workspace
        mvn package
