apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone $(params.url) $(workspaces.shared-workspace.path)
  params:
    - name: url
      type: string
      description: The URL of the Git repository to clone
