apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: lint
      image: maven:3.6.3-jdk-8
      script: |
        mvn checkstyle:check
