apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: lint
      image: maven:3.6.3-jdk-8
      script: |
        cd /workspace/shared-workspace/clone-dir
        mvn com.github.ekryd:maven-lint-plugin:check --fail-at-end || echo "Linting issues found but continuing"
