apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: lint
      image: quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java11
      workingdir: /workspace/shared-workspace/clone-dir
      script: |
         mvn checkstyle:check

