apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image-task
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      env:
        - name: REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-hub-secret
              key: DOCKER_USERNAME
        - name: REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-hub-secret
              key: DOCKER_PASSWORD
        - name: REGISTRY_URL
          value: docker.io 
      script: |
        buildah --storage-driver vfs login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD" "$REGISTRY_URL"
        buildah --storage-driver vfs bud -f /workspace/shared-workspace/clone-dir/src/main/docker/Dockerfile.jvm -t "$REGISTRY_URL/$REGISTRY_USERNAME/quarkus-rh:latest" /workspace/shared-workspace/clone-dir
        buildah --storage-driver vfs push "$REGISTRY_URL/$REGISTRY_USERNAME/quarkus-rh:latest"
