apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
  namespace: quarkus-ci
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: test
      image: maven:3.6.3-jdk-17
      script: |
        cd /workspace/shared-workspace/clone-dir
        mvn test
