apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-task
spec:
  steps:
    - name: update
      image: alpine/git
      script: |
        git clone https://github.com/my-org/cicd-repo.git
        cd cicd-repo/k8s/stage
        sed -i 's|quay.io/my-repo/quarkus-app:.*|docker.io/arthurdbs/quarkus-app:latest|' deployment.yaml
        git commit -am "Update image to docker.io/arthurdbs/quarkus-app:latest"
        git push
